(ns clojure-playground)
(println (type 1))
(println (type 1.1))
(println (type true))
(println (type "Hello"))
(println (type (keyword "a")))
(println (type (quote a)))
(println (type 'a))
(println (type (list 1 2 3)))
(println (type (vector 1 2 3)))
(println (nth (vector 1 2 3) 2))
(println (first (list 1 2 3 4)))
